public_url = 'http://$WALLET_REACHABLE_ADDRESS:3009/'
issuer_trust_anchors = ["${ISSUER_CA_CRT}", "${ISSUER_PID_CA_CRT}"]
reader_trust_anchors = ["$READER_CA_CRT"]

ephemeral_id_secret = "$EPHEMERAL_ID_SECRET"
allow_origins = ["http://localhost:8000", "http://127.0.0.1:8000"]

universal_link_base_url = "https://app.demo.voorbeeldwallet.nl/deeplink/"

# log_requests = true

[storage]
url = 'postgres://postgres:postgres@localhost:5432/verification_server'

[wallet_server]
ip = '0.0.0.0'
port = 3009

[requester_server]
ip = '0.0.0.0'
port = 3010

[usecases.myusecase]
certificate = "$CRT_READER"
private_key = "$KEY_READER"
private_key_type = "software"
